### ISSUE TITLE
페이지 96, 오탈자

### ISSUE THREAD

**Issue by jaehyukpyon** [stepanowon/vue3-quickstart#1]
안녕하세요 저자님,

페이지 96에 오탈자로 의심되는 부분이 있어 issue 작성해둡니다.

본문 두 번째 줄부터 "컴포넌트 인스턴스가 생성되고 관찰이 시작되면 루트 data 객체에는 반응성을 **지난** 속성을 더이상 추가할 수 없습니다."

**지난** 이 아닌, **지닌**이 맞을 것 같습니다.
확인 부탁드립니다. 감사합니다.

**Comment by stepanowon** [comment]
오타 지적 감사합니다.

재혁님께서 보내주신 내용 다음과 같이 반영하였습니다.  다시 한번 감사드립니다.

https://github.com/stepanowon/vue3-quickstart/blob/main/%EC%A0%95%EC%98%A4%ED%91%9C.MD

________________________________
보낸 사람: Jaehyuk Pyon ***@***.***>
보낸 날짜: 2023년 7월 20일 목요일 19:45
받는 사람: stepanowon/vue3-quickstart ***@***.***>
참조: Subscribed ***@***.***>
제목: [stepanowon/vue3-quickstart] 페이지 96, 오탈자 (Issue #1)


안녕하세요 저자님,

페이지 96에 오탈자로 의심되는 부분이 있어 issue 작성해둡니다.

본문 두 번째 줄부터 "컴포넌트 인스턴스가 생성되고 관찰이 시작되면 루트 data 객체에는 반응성을 지난 속성을 더이상 추가할 수 없습니다."

지난 이 아닌, 지닌이 맞을 것 같습니다.
확인 부탁드립니다. 감사합니다.
