### ISSUE TITLE
페이지 147, 오탈자

### ISSUE THREAD

**Issue by jaehyukpyon** [stepanowon/vue3-quickstart#2]
안녕하세요 저자님,

페이지 147에 오탈자로 의심되는 부분이 있어서 issue를 작성해둡니다.

코드가 작성된 부분 말고, 아래 본문 세 번째 줄부터 읽어보면,
"12행의 style1 데이터 속성을 살펴보면 backgroundColor, **textAlign**과 같이 카멜 표기법을 사용하여 자바스크립트 객체로 초기 스타일을 (중략)..." 라고 적혀 있습니다.

하지만 실제 코드 부분(예제 06-02)의 12행을 보면 **textAlign** 이 아닌, **color** 가 적혀져 있습니다.

이 부분이 오탈자로 의심돼서요...
확인 부탁드립니다. 감사합니다.

**Comment by stepanowon** [comment]
그것은 오타가 아닙니다. 12행의 스타일의 속성값 하나하나를 가리키는 것이 아닌  스타일 객체를 작성할 때  camel Casing 규칙을 사용한다는 점을 설명한 부분입니다.
