### ISSUE TITLE
페이지 211 오탈자

### ISSUE THREAD

**Issue by jaehyukpyon** [stepanowon/vue3-quickstart#3]
안녕하세요 저자님, 
먼저, 바로 이전 issue에서 제가 잘못 이해한 상태로 오탈자 문의를 드린 점 죄송합니다.

페이지 211의 그림 07-28을 보면, 
오른쪽 맨 아래 여러 개의 네모 사각형이 그려진 것의 컴포넌트 명이 **TodoList**가 아닌, **TodoListItem**이 맞을 것 같습니다.

또한 페이지 212의 04번째 라인 classe -> **class**
확인 부탁드립니다. 감사합니다.

**Comment by stepanowon** [comment]
오탈자 맞습니다. 찾아주셔서 감사합니다.
다음과 같이 정정하였습니다.

https://github.com/stepanowon/vue3-quickstart/blob/main/%EC%A0%95%EC%98%A4%ED%91%9C.MD
