### ISSUE TITLE
페이지 264 중복 코드

### ISSUE THREAD

**Issue by lakesoi** [stepanowon/vue3-quickstart#6]
Modal.vue 예제 코드를 보면 background-color를 두 번 설정하고 있습니다.
첫 번째 배경 설정 코드는 필요 없지 않나요?

    background-color: rgb(0, 0, 0);
    background-color: rgba(0, 0, 0, 0.4);

**Comment by stepanowon** [comment]
감사합니다. 정오표에 반영하였습니다.

**Comment by lakesoi** [comment]
안녕하세요. 동일한 오류가 334페이지 예제 코드의 모달 클래스 스타일을 정의하는 부분에도 있습니다.

**Comment by stepanowon** [comment]
감사합니다. 264페이지 코드의 Model Style을 그대로 카피하면서 중복된 부분까지 그대로 사용했었네요. 중복 지적 감사합니다.
정오표에 반영하였습니다.
