### ISSUE TITLE
페이지 459 오류

### ISSUE THREAD

**Issue by lakesoi** [stepanowon/vue3-quickstart#8]
예제 13-07 코드를 보면
12라인의 import { useTodoListStore } from '@/stores/todoList.js' 이 아닌
13라인의 import Loading from './components/Loading.vue'; 에 bold가 적용 되어 있습니다.

Loading component의 경우 12장 예제에서 이미 추가되어 있던 내용이고, 12라인의 store 관련 내용이 13장에서 추가되는 내용인 것으로 봐서는 bold가 12라인에 적용되어야 할 것 같습니다.

**Comment by stepanowon** [comment]
책을 꼼꼼히 읽어주셔서 감사합니다. 12행이 볼드처리되는 것이 맞습니다. 지적 감사합니다.
