### ISSUE TITLE
그림 03-22 내용 상이로 인한 이슈 요청

### ISSUE THREAD

**Issue by byounghoonmoon** [stepanowon/vue3-quickstart#9]
안녕하세요 선생님 ~~ ㅎㅎ책 과 강의 잘 듣고 있습니다.

페이지 80에 `그림 03-22` 과 코드 결과값이 상이하여 issue 작성 합니다.

5~7행 내용중 번호와 전화번호가 4행과 동일합니다. 

- **책에 표기된 내용**
<img width="609" alt="image" src="https://github.com/stepanowon/vue3-quickstart/assets/25805562/39f9ec43-1ddf-41d5-a90c-7999775053ec">

- **실제 내용**
<img width="619" alt="image" src="https://github.com/stepanowon/vue3-quickstart/assets/25805562/e92e8247-838d-4f73-a182-bb13cd8c2ce4">

확인 부탁드립니다.
감사합니다.

**Comment by stepanowon** [comment]
진심으로 감사드립니다.

아마도 제가 원고를 쓰면서 화면캡춰할 때 데이터를 일부 변경하지 않고 했던 것 같습니다.
코드는 문제가 없고 테스트에 지장이 없어서 정오표에는 반영하지 않고 다음번 인쇄를 찍을 때 반영하도록 하겠습니다.

다시 한번 감사드립니다.
